development:
  adapter: postgresql
  encoding: unicode
  database: productlisting
  username: rails
  password: 'asd123!@#'
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: productlisting
  username: rails
  password: 'asd123!@#'
  host: 127.0.0.1
